config/routes.rb
Rails.application.routes.draw do
  # root "welcome#home"
  resources :sessions
  resources :users
  resources :events
  root 'events#index'

  get "signup", to: "users#new"
  get "signin", to: "sessions#new"
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'attend_event', to: 'user_events#create'
  get 'user_events', to: 'user_events#show'
  # get 'attendees', to: 'events#show'

  # get  'events', to: 'events#new'
  # post 'events', to: 'events#create'
  # get  'events', to: 'events#show'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
  has_many :user_events, foreign_key: 'event_id'
  has_many :attendees, through: :user_events, source: :user
  scope :upcoming, -> { where('event_date > ?', Time.zone.now) }
  scope :past, -> { where('event_date <= ?', Time.zone.now) }

  validates :event_name, presence: true, length: { minimum: 3, maximum: 25 }
  validates :event_date, presence: true
  validates :location, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 3, maximum: 250 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ActiveRecord::Base
  attr_accessor :gen_token
  before_create :create_token_and_save
  before_save { self.email = email.downcase }

  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze

  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 25 },
                    format: { with: VALID_EMAIL_REGEX }

  has_many :events, foreign_key: :creator_id
  has_many :user_events, foreign_key: 'user_id'
  has_many :attended_events, through: :user_events, source: :event

  has_secure_password

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypted(string)
    Digest::SHA1.hexdigest(string.to_s)
  end

  def create_token_and_save
    self.gen_token = User.new_token
    self.remember_digest = User.encrypted(gen_token)
  end
end

app/models/user_event.rb
# frozen_string_literal: true

class UserEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def require_user
    return if logged_in?

    flash[:danger] = 'You must log in to perform that action'
    redirect_to root_path
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def sign_in
    session[:user_id] = user.id
    cookies.permanent.signed[:user_id] = user.id
    user.create_token_and_save
    cookies.permanent[:remember_digest] = user.remember_digest
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :require_login, only: %i[new show create]

  def index
    @events = Event.all
    @upcoming_events = @events.upcoming
    @past_events = @events.past
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = current_user.events.build(event_params)
    @event.creator = current_user
    if @event.save
      flash[:success] = 'Event successfully created'
      redirect_to events_path
    else
      flash[:danger] = 'something went wrong'
      render 'new'
    end
  end

  def destroy
    @event = current_user.events.find(params[:id])
    @event.destroy
    flash[:success] = 'Event has been deleted'
    redirect_to root_path
  end

  private

  def require_login
    logged_in?
    flash[:danger] = 'You must be logged in to access this section'
    redirect_to root_path
  end

  def set_event
    @event = current_user.events.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:event_name, :event_date, :description, :location)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'You have successfully logged in'
      redirect_to user_path(user)
    else
      flash.now[:danger] = 'There is something wrong with your login information'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have logged out'
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/user_events_controller.rb
# frozen_string_literal: true

class UserEventsController < ApplicationController
  before_action :logged_in?
  before_action :require_login, only: %i[new show]

  def create
    if UserEvent.find_by(user_id: params[:user_id], event_id: params[:event_id]).nil?
      @userevent = UserEvent.new(user_id: params[:user_id], event_id: params[:event_id])
      flash.now[:success] = 'Registration Successful !!!' if @userevent.save
    else

      flash.now[:danger] = 'Not Successful!!!'
    end
    redirect_to root_path
  end

  private

  def require_login
    logged_in?
    flash[:danger] = 'You must be logged in to access this section'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @user_events = @user.events
    @past_events = @user.attended_events.past
    @upcoming_events = @user.attended_events.upcoming
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Private Events #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def home; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
  def create_event_button
    return unless logged_in?

    link_to 'Create Event', new_event_path, class: 'btn btn-secondary text-white'
  end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/user_events_helper.rb
# frozen_string_literal: true

module UserEventsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/events/_attend_event.html.erb
<% if logged_in?  %>
    <%= link_to "Attend Event", attend_event_path(user_id: current_user, event_id: event.id), class: "btn btn-secondary", data: { confirm: "Are you sure you want to attend this event?"}%>
<% end %>

app/views/events/index.html.erb
<h1 align="center" class="my-4">Private Events</h1>

<%= create_event_button %>
<h3 align="center" class="text-danger">Past events (<%= @past_events.count%>)</h3>
        <% @past_events.each do |event| %>
            <div class =" card col-9 mx-auto bg-light my-3">
                <div><strong>Event name: </strong><%= event.event_name %></div>
                <div><strong>Event date: </strong><%= event.event_date %></div>
                <div><strong>description: </strong><%= event.description %></div>
                <div><strong>location: </strong><%= event.location %></div>
                <small class="text-success font-small">Created by: <%= event.creator.username %>  |  
                    <%= time_ago_in_words(event.created_at) %> ago  |  
                    last updated: <%= time_ago_in_words(event.updated_at) %> ago</small><br>
            </div>
        <% end %>


    <h3 align="center" class="text-success">Upcoming events (<%= @upcoming_events.count%>)</h3>
        <% @upcoming_events.each do |event| %>
            <div class =" card col-9 mx-auto bg-light my-3">
                <div><strong>Event name: </strong><%= event.event_name %></div>
                <div><strong>Event date: </strong><%= event.event_date %></div>
                <div><strong>description: </strong><%= event.description %></div>
                <div><strong>location: </strong><%= event.location %></div>
                <small class="text-success font-small">Created by: <%= event.creator.username %>  |  
                    <%= time_ago_in_words(event.created_at) %> ago  |  
                    last updated: <%= time_ago_in_words(event.updated_at) %> ago</small><br>
                <% if logged_in?  %>
                <%= link_to "Attend Event", attend_event_path(user_id: current_user, event_id: event.id), class: "btn btn-secondary", data: { confirm: "Are you sure you want to attend this event?"}%>
                <% end %>
            </div>
        <% end %>
<%
=begin%>
 <% @events.each do |event| %>
    <div class="mx-auto col-9 bg-light my-3 p-3">
    <strong class="text-success" >Event Name: </strong><%= event.event_name %><br>
    <strong class="text-success">Date: </strong ><%= event.event_date %><br>
    <strong class="text-success" >Description: </strong><%= event.description %><br>
    <strong class="text-success">Host: </strong><%= event.location %><br>
 
 <small class="text-success font-small">Created by: <%= event.creator.username %>  |  
                   <%= time_ago_in_words(event.created_at) %> ago  |  
                   last updated: <%= time_ago_in_words(event.updated_at) %> ago</small><br> 


    <% if logged_in?  %>
    <%= link_to "Attend Event", attend_event_path(user_id: current_user, event_id: event.id), class: "btn btn-secondary", data: { confirm: "Are you sure you want to attend this event?"}%>

    <% end %>
    </div>        
<% end %> 
<%
=end%>

app/views/events/new.html.erb
<h1 align="center" class="my-3 font-weight-bolder">Create Event</h1>

<%= form_for(@event, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group row">
    <div class="control-label col-sm-2 ">
        <%= f.label :event_name, class: "font-weight-bolder" %>
    </div>
    <div class="col-sm-8">
        <%= f.text_field :event_name, class: "form-control", placeholder: "Event name", autofocus: true %>
    </div>
    </div>

    <div class="form-group row">
    <div class="control-label col-sm-2 ">
        <%= f.label :event_date, class: "font-weight-bolder" %>
    </div>
    <div class="col-sm-8">
        <%= f.date_field :event_date, class: "form-control", placeholder: "Event date", autofocus: true %>
    </div>
    </div>

    <div class="form-group row">
    <div class="control-label col-sm-2 ">
        <%= f.label :location, class: "font-weight-bolder" %>
    </div>
    <div class="col-sm-8">
        <%= f.text_field :location, class: "form-control", placeholder: "Event Location ", autofocus: true %>
    </div>
    </div>

    <div class="form-group row">
    <div class="control-label col-sm-2">
        <%= f.label :description, class: "font-weight-bolder" %>
    </div>
    <div class="col-sm-8">
        <%= f.text_area :description, rows: 6, class: "form-control", placeholder: "Event description", autofocus: true %>
    </div>
    </div>

    <div class="form-group row py-2 text-center">
    <div class="col-sm-10 mx-5">
        <%= f.submit  class: "btn btn-secondary " %>
        <%= link_to "Go Back to Events", events_path, class: "btn btn-secondary " %>
    </div>
    </div>

<% end %>

app/views/events/show.html.erb
<%
=begin%>
 <h1 align="center">Show Created Event</h1> 
<%
=end%>
  <div class="card col-9 bg-light mx-auto mt-5">
      <div><strong class="text-success" >Event Name: </strong><%= @event.event_name %>
      <div><strong class="text-success">Date: </strong ><%= @event.event_date.to_date.strftime("%m/%d/%Y") %> </div>
      <div><strong class="text-success" >Description: </strong><%= @event.description %>
      <div><strong class="text-success">Host: </strong><%= @event.creator.username %> (<%= @event.creator.email %>)</div>
    
      <hr>

      <div class="field text-warning"> <h4>Attendees: </h4></div>
      <% if @event.attendees.any? %> 
        <ul class="list-unstyled">
          <% @event.attendees.each do |attendee| %>
            <li> <strong>Name: </strong><%= attendee.username %></li>
            <li><strong>Email: </strong><%= attendee.email %></li>
            <% if @event.attendees.count > 1%> <hr> <% end %>
          <% end %>
        </ul>
      <% else %>
        This event has no attendees
      <% end %>
  </div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-secondary ">
  <%= link_to "Private Event", root_path, class: "navbar-brand text-white font-weight-bolder", id: "logo" %>
  <button class="navbar-toggler text-white" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon text-white"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto ">
      <li class="nav-item ">
        <%= link_to "View Events", events_path, class: "nav-link text-white", id: "event_all" %>
      </li>
      <% if logged_in? %>
      <li class="nav-item">
        <%= link_to  "Create Event", new_event_path, class: "nav-link text-white" %>
      </li>
      <% end %>
    </ul>
 
    <ul class="nav navbar-nav navbar-right mx-1">
    <% if logged_in? %>

      <li class="nav-item">
        <%= link_to  "Profile: #{current_user.username} ", user_path(current_user), class: "nav-link text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Log out', logout_path, method: :delete, class: "btn btn-outline-dark my-2 my-sm-0 nav-link text-white" %>
      </li>
      
      <% else %>
      <li class="nav-item mx-1">
        <%= link_to  "SIGN IN", signin_path, class: "btn btn-outline-dark my-2 my-sm-0 nav-link text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to 'SIGN UP', signup_path, class: "btn btn-outline-dark my-2 my-sm-0 nav-link text-white" %>
      </li>
      <% end %>
      </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <%= render "layouts/navigation" %>

    <% flash.each do |name, msg| %>
            <div class='alert alert-<%="#{name}" %>'>
            <a href="#" class="close" data-dismiss="alert">&#215;</a>
            <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
            </div>
    <% end %>

    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<h1 align="center" class="my-3 font-weight-bolder"> SIGNUP </h1>

<%= form_for @user do |f| %>
    <div class="form-group row">
    <div class="control-label col-sm-2 ">
        <%= f.label :username, class: "font-weight-bolder" %> 
    </div>
    <div class="col-sm-8">
        <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
    </div>
    </div>

    <div class="form-group row">
    <div class="control-label col-sm-2">
        <%= f.label :email, class: "font-weight-bolder" %>
    </div>
    <div class="col-sm-8">
        <%= f.email_field :email, class: "form-control", placeholder: "Enter email", autofocus: true %>
    </div>
    </div>

    <div class="form-group row">
    <div class="control-label col-sm-2">
        <%= f.label :password, class: "font-weight-bolder" %>
    </div>
    <div class="col-sm-8">
        <%= f.password_field :password, class: "form-control", placeholder: "Enter password", autofocus: true %>
    </div>
    </div>

    <div class="form-group row py-2 text-center">
    <div class="col-sm-10 mx-5">
        <%= f.submit "Sign up", class: "btn btn-secondary" %>
        <%= link_to "Go Back to Events", events_path, class: "btn btn-secondary " %>
    </div>
    </div>

<% end %>

app/views/users/show.html.erb
    <h5 align="right" class="text-secondary">WELCOME <%= @user.username.upcase %>!!!!!!!!!</h5>


    <%= link_to  "Create Event", new_event_path, class: "btn btn-secondary text-white" %>
    <div class="row">
        <h2 class="text-success col">Upcoming Events (<%= @upcoming_events.count%>)</h2>
        <h2 class="text-danger col ">Past Events (<%= @past_events.count%>)</h2>
        <h2 class="text-primary col">Attending Events (<%= @user.attended_events.count%>)</h2>
    </div>
    
    <h1 align="center" class="text-info" >My events: </h1>
    <% @user_events.each do |event| %>
        <div class="mx-auto col-9 bg-light my-3 p-3 card">
        <%= event.event_name %><br>
        <%= event.event_date %><br>
        <%= event.description %><br>
        <%= event.location %><br>
    
        <small class="text-success font-small">Created by: <%= event.creator.username %>  |  
                    <%= time_ago_in_words(event.created_at) %> ago  |  
                    last updated: <%= time_ago_in_words(event.updated_at) %> ago</small><br> 
        </div>        
    <% end %>

    <h3 align="center" class="text-danger">Past events</h3>
        <% @past_events.each do |event| %>
            <div class =" card col-9 mx-auto bg-light my-3">
                <div><strong>Event name: </strong><%= event.event_name %></div>
                <div><strong>Event date: </strong><%= event.event_date %></div>
                <div><strong>description: </strong><%= event.description %></div>
                <div><strong>location: </strong><%= event.location %></div>
            </div>
        <% end %>


    <h3 align="center" class="text-success">Upcoming events</h3>
        <% @upcoming_events.each do |event| %>
            <div class =" card col-9 mx-auto bg-light my-3">
                <div><strong>Event name: </strong><%= event.event_name %></div>
                <div><strong>Event date: </strong><%= event.event_date %></div>
                <div><strong>description: </strong><%= event.description %></div>
                <div><strong>location: </strong><%= event.location %></div>
            </div>
        <% end %>

       
    

app/views/welcome/home.html.erb
<h1>HOME PAGE</h1>

<h1><%= link_to  "sign up", signup_path %></h1>
<h1><%= link_to  "sign in", signin_path %></h1>